### ISSUE TITLE
problem putting shear on NFW lens in twalk

### ISSUE THREAD

**Issue by kevinea42** [qminor/qlens-beta#3] opened 2017-11-12 21:07 UTC
I am using twalk, trying to put in an NWF lens, with "shear components on", as follows:

`fit lens nfw            3     9.085    0.7     132.5    0.0     0.1 shear=0.0  0.1
                        1        1      1        1      1       1       1     1
0.2  50
2    200
.2   1
100  170
-4    4
-4    4 

-2.   2.
-2.   2.`

The output looks like this:
`limits for parameter ks:
0.2  50
limits for parameter rs:
2    200
limits for parameter q:
.2   1
limits for parameter theta:
100  170
limits for parameter xc:
-4    4
limits for parameter yc:
-4    4 

-2.   2.
Error: command not recognized`

Am I doing something wrong?

**Comment by qminor** [comment] 2017-11-13 02:39
Hi Kevin,

No, QLens should not have a problem with this...I had a hard time reproducing this on my machine, but when I did, it seemed that recompiling everything made it go away. Try the following in the qlens directory:

```
make clean_qlens
make
```

Then run it again, and let me know if you get the same error.

**Comment by kevinea42** [comment] 2017-11-13 02:46
I tried recompiling, to no avail.  Here is my input script and data file. Perhaps I am doing something wrong. Thanks much!




On Nov 12, 2017, at 6:39 PM, qminor <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Kevin,

No, QLens should not have a problem with this...I had a hard time reproducing this on my machine, but when I did, it seemed that recompiling everything made it go away. Try the following in the qlens directory:

make clean_qlens
make


Then run it again, and let me know if you get the same error.

**Comment by kevinea42** [comment] 2017-11-13 03:24
I did git pull, and recompiled, but still same error.  Here is my Makefile.



On Nov 12, 2017, at 7:06 PM, qminor <notifications@github.com<mailto:notifications@github.com>> wrote:


It's possible the compiler on your machine is being slightly picky about one line of code. I made a slight change to commands.cpp to check this. Can you do a 'git pull', recompile and see if the error is still there?

**Comment by qminor** [comment] 2017-11-13 20:27
Looks like that solved the problem! Closing this issue now.

**Closed by qminor** 2017-11-13 20:27 UTC
